#[derive(Clone, Copy)]
pub(crate) struct ContentPageSpec {
    pub(crate) slug: &'static str,
    pub(crate) title_key: &'static str,
    pub(crate) lead_key: &'static str,
    pub(crate) text_key: &'static str,
    pub(crate) default_title: &'static str,
    pub(crate) default_lead: &'static str,
    pub(crate) default_text: &'static str,
}

pub(crate) const CONTENT_PAGES: &[ContentPageSpec] = &[
    ContentPageSpec {
        slug: "about",
        title_key: "aboutPageTitle",
        lead_key: "aboutPageLead",
        text_key: "aboutPageText",
        default_title: "О компании Sobag Opt",
        default_lead: "Sobag Opt — B2B-каталог для оптовых продаж текстиля с принтами и заказов на производство под макет покупателя.",
        default_text: "Мы работаем с магазинами, селлерами и корпоративными клиентами: помогаем подобрать товар, собрать партию, рассчитать скидку, подготовить упаковку и передать заказ в производство.",
    },
    ContentPageSpec {
        slug: "business",
        title_key: "businessPageTitle",
        lead_key: "businessPageLead",
        text_key: "businessMinimumText",
        default_title: "Условия для бизнеса",
        default_lead: "Условия для магазинов, селлеров и корпоративных клиентов: скидка от суммы заказа, производство в одном месте и сопровождение менеджера.",
        default_text: "Минимальная сумма для оформления оптовой заявки — 30 000 ₽. До этой суммы товары можно добавлять в корзину, сохранять подборку и готовить заказ к отправке менеджеру.",
    },
    ContentPageSpec {
        slug: "marketplaces",
        title_key: "marketplacesTitle",
        lead_key: "marketplacesText",
        text_key: "marketplaceOneText",
        default_title: "Мы на маркетплейсах",
        default_lead: "Готовые товары Sobag можно смотреть на витринах маркетплейсов, а оптовые партии и индивидуальные принты оформлять через этот сайт.",
        default_text: "Витрины подходят для просмотра части готового ассортимента Sobag.",
    },
    ContentPageSpec {
        slug: "contacts",
        title_key: "contactsPageTitle",
        lead_key: "contactsPageLead",
        text_key: "contactsSchedule",
        default_title: "Контакты",
        default_lead: "Свяжитесь с отделом опта, чтобы уточнить наличие, сроки запуска партии, упаковку, отгрузку и документы.",
        default_text: "Пн-Пт, 10:00-18:00 по Москве",
    },
    ContentPageSpec {
        slug: "how-to-order",
        title_key: "howToOrderPageTitle",
        lead_key: "howToOrderPageLead",
        text_key: "howToOrderPageText",
        default_title: "Как оформить заказ",
        default_lead: "Покупатель собирает товары в корзину, проверяет скидку и отправляет заявку менеджеру.",
        default_text: "Добавьте нужные варианты товара, перейдите в корзину, заполните контакты и отправьте заказ. Менеджер проверит наличие, сроки, упаковку, документы и подтвердит финальные условия.",
    },
    ContentPageSpec {
        slug: "delivery",
        title_key: "deliveryPageTitle",
        lead_key: "deliveryPageLead",
        text_key: "deliveryPageText",
        default_title: "Доставка товара",
        default_lead: "Способ доставки и город отгрузки согласуются после проверки оптовой заявки.",
        default_text: "Доставка рассчитывается после подтверждения состава заказа, веса, объема и требований к упаковке. Возможны самовывоз, транспортная компания или индивидуальная схема отгрузки.",
    },
    ContentPageSpec {
        slug: "payment",
        title_key: "paymentPageTitle",
        lead_key: "paymentPageLead",
        text_key: "paymentPageText",
        default_title: "Оплата товара",
        default_lead: "Оплата фиксируется после согласования заказа, счета и реквизитов.",
        default_text: "Для юридических лиц и ИП возможна оплата по счету. Финальный порядок оплаты, резерв товара и документы подтверждает менеджер перед запуском партии.",
    },
    ContentPageSpec {
        slug: "returns",
        title_key: "returnsPageTitle",
        lead_key: "returnsPageLead",
        text_key: "returnsPageText",
        default_title: "Возврат товара",
        default_lead: "Вопросы возврата и претензий решаются по согласованным условиям заказа.",
        default_text: "Если в партии есть расхождения по количеству, комплектности или качеству, зафиксируйте их фото и описанием. Менеджер проверит обращение и предложит решение.",
    },
    ContentPageSpec {
        slug: "seller-support",
        title_key: "sellerSupportPageTitle",
        lead_key: "sellerSupportPageLead",
        text_key: "sellerSupportPageText",
        default_title: "Поддержка селлеров",
        default_lead: "Помощь с упаковкой, маркировкой и подготовкой партий для маркетплейсов.",
        default_text: "Можно согласовать штрихкоды, упаковку, комплектацию, маркировку и требования площадок. Детали фиксируются до запуска партии в производство.",
    },
    ContentPageSpec {
        slug: "wholesale",
        title_key: "wholesalePageTitle",
        lead_key: "wholesalePageLead",
        text_key: "wholesalePageText",
        default_title: "Оптовые партии",
        default_lead: "Партии собираются из готовых позиций и изделий под макет клиента.",
        default_text: "Оптовая партия может включать разные изделия, размеры, материалы и принты. Скидка зависит от суммы корзины, а сроки запуска подтверждаются после проверки состава заказа.",
    },
];
