(() => {
  "use strict";

const TYPE_OPTIONS = ["Подушка", "Наволочка"];
const SIZE_OPTIONS = ["30x30", "35x35", "40x40", "45x45", "50x50"];
const MATERIAL_OPTIONS = ["Велюр", "Габардин"];

const sizeFactors = {
  "30x30": 0,
  "35x35": 35,
  "40x40": 70,
  "45x45": 115,
  "50x50": 160,
  "30x40": 70,
  "35x45": 115,
  "40x50": 160,
  Стандарт: 120,
  XL: 240,
};

const materialFactors = {
  Габардин: 0,
  Велюр: 90,
  Оксфорд: 70,
};

const typeFactors = {
  Наволочка: 0,
  Подушка: 180,
  Мешок: 40,
  Чехол: 120,
};

const quantityTiers = [
  { qty: 30, discount: 3 },
  { qty: 70, discount: 7 },
  { qty: 150, discount: 12 },
  { qty: 300, discount: 18 },
];

const MIN_CART_TOTAL = 30000;
const basketDiscountTiers = [
  { amount: MIN_CART_TOTAL, discount: 5 },
  { amount: 70000, discount: 7 },
  { amount: 150000, discount: 12 },
  { amount: 300000, discount: 18 },
];

const catalogCategories = [
  {
    name: "Подушки",
    icon: "square-stack",
    description: "Оптовые декоративные подушки с принтами, наполнителем и вариантами размеров для магазинов, подарочных витрин и маркетплейсов.",
  },
  {
    name: "Наволочки",
    icon: "panel-top",
    description: "Съемные наволочки под готовые линейки и сезонные коллекции: удобно обновлять витрину без замены наполнителя.",
  },
  {
    name: "Пледы",
    icon: "layers",
    description: "Пледы с полноцветными принтами для подарочных, интерьерных и корпоративных партий с подбором дизайнов под аудиторию.",
  },
  {
    name: "Мешки для обуви",
    icon: "package",
    description: "Легкие мешки для обуви и сменной формы для школ, спорта, сувенирных наборов и брендированного мерча.",
  },
  {
    name: "Чехлы на кулер",
    icon: "container",
    description: "Текстильные чехлы на кулер под корпоративные заказы, промоакции и оформление офисных зон.",
  },
  {
    name: "Чехлы на чемодан",
    icon: "briefcase",
    description: "Принтованные чехлы на чемодан для тревел-витрин, подарочных наборов и маркетплейс-поставок.",
  },
  {
    name: "Ремувки",
    icon: "tag",
    description: "Текстильные ремувки и аксессуары с принтами для мерча, сувенирных партий, брендирования и комплектов к основным изделиям.",
  },
  {
    name: "Флаги",
    icon: "flag",
    description: "Флаги и декоративный текстиль с печатью для тематических витрин, мероприятий, промо-наборов и корпоративных заказов.",
  },
];

const catalogCollections = [
  { name: "Абстракция", icon: "shapes", description: "Абстрактные принты для интерьерных линеек, подарочных витрин и универсального ассортимента без привязки к сезону." },
  { name: "Авто", icon: "car", description: "Автомобильные сюжеты для подарков водителям, тематических магазинов, мужских подборок и маркетплейс-поставок." },
  { name: "Анимализм", icon: "paw-print", description: "Принты с животными мотивами для семейных, детских, интерьерных и подарочных партий текстиля." },
  { name: "Аниме", icon: "sparkles", description: "Подборка принтов в аниме-стилистике для молодежных витрин, фан-мерча и тематических партий." },
  { name: "Брейнрот", icon: "zap", description: "Трендовые мемные сюжеты для быстрых запусков, молодежных коллекций и ассортимента с высокой обновляемостью." },
  { name: "Военные", icon: "shield", description: "Строгие тематические дизайны для сезонных заявок, сувенирных наборов и патриотических коллекций." },
  { name: "Геометрия", icon: "grid-3x3", description: "Геометрические паттерны для спокойных интерьерных серий, базовых полок и регулярных допоставок." },
  { name: "Гуси", icon: "feather", description: "Ироничные сюжеты с гусями для подарочных витрин, маркетплейсов и легких сезонных коллекций." },
  { name: "Детские", icon: "baby", description: "Детские принты для подарков, школьных закупок, семейных магазинов и мягких интерьерных изделий." },
  { name: "Детские паттерны", icon: "blocks", description: "Повторяющиеся детские рисунки для комплектов, наволочек, подушек и других изделий в единой серии." },
  { name: "Для девочек", icon: "heart", description: "Нежные и яркие дизайны для детских подарков, семейных витрин и персональных коллекций." },
  { name: "Для мальчиков", icon: "rocket", description: "Динамичные детские сюжеты для подарочных партий, школьных закупок и тематических наборов." },
  { name: "Мемы", icon: "message-circle", description: "Ироничные и узнаваемые принты для быстрых розничных запусков, подарочных полок и маркетплейсов." },
  { name: "Животные", icon: "paw-print", description: "Коллекция с декоративными сюжетами для семейных магазинов, подарков и уютных интерьерных линеек." },
  { name: "Знаки зодиака", icon: "sparkle", description: "Зодиакальные принты для персональных подарков, тематических подборок и круглогодичных маркетплейс-продаж." },
  { name: "Именные", icon: "type", description: "Персонализируемые макеты для именных подарков, небольших серий и расширения ассортимента без новой формы изделия." },
  { name: "Интерьерные", icon: "sofa", description: "Спокойные интерьерные дизайны для дома, подарочных комплектов, регулярных полок и универсальных оптовых партий." },
  { name: "Ислам", icon: "moon-star", description: "Тематические дизайны для уважительных подарочных подборок, сезонных заказов и специализированного ассортимента." },
  { name: "Камуфляж", icon: "scan", description: "Камуфляжные паттерны для тематических коллекций, сувенирных партий и практичного повседневного мерча." },
  { name: "Мофу", icon: "smile", description: "Мягкие kawaii-сюжеты для молодежных витрин, подарков, фан-мерча и быстрых обновлений ассортимента." },
  { name: "Найк", icon: "badge", description: "Спортивная визуальная стилистика для молодежных подборок и динамичных товаров с принтами." },
  { name: "Однотонные", icon: "square", description: "Базовые однотонные решения для спокойных комплектов, корпоративных партий и ассортимента без яркого рисунка." },
  { name: "Паттерны", icon: "palette", description: "Повторяющиеся орнаменты и графика для спокойных интерьерных серий, базовых полок и регулярных допоставок." },
  { name: "Поп-арт", icon: "paintbrush", description: "Яркие поп-арт принты для заметных витрин, подарочных серий и товаров с выразительным визуальным акцентом." },
  { name: "Прикол", icon: "laugh", description: "Юмористические дизайны для подарков, мемных подборок, маркетплейсов и быстрых сезонных запусков." },
  { name: "Религия", icon: "landmark", description: "Тематические принты для специализированных подарочных подборок и уважительных сезонных коллекций." },
  { name: "Русский Стиль", icon: "landmark", description: "Дизайны в русской стилистике для сувенирных партий, тематических витрин и подарочных коллекций." },
  { name: "Спорт", icon: "dumbbell", description: "Спортивные сюжеты для подарков, командных подборок, активного мерча и молодежных коллекций." },
  { name: "Страна", icon: "map", description: "Географические и страновые мотивы для тревел-витрин, сувениров, подарков и тематических партий." },
  { name: "Тревел", icon: "plane", description: "Дизайны про путешествия для чехлов, подарочных наборов, сезонных витрин и маркетплейс-поставок." },
  { name: "Футбол", icon: "circle-dot", description: "Футбольные мотивы для фан-мерча, подарков болельщикам, спортивных коллекций и сезонных заявок." },
  { name: "Цветы", icon: "flower-2", description: "Цветочные принты для весенних подарков, интерьерных изделий, женских коллекций и регулярных витрин." },
  { name: "Япония", icon: "circle", description: "Японская визуальная стилистика для молодежных подборок, подарочного текстиля и тематического мерча." },
  { name: "Игры", icon: "gamepad-2", description: "Тематические игровые принты для молодежных коллекций, сувенирных партий и промо-наборов." },
  { name: "Космос", icon: "orbit", description: "Космические мотивы для детских, подростковых и подарочных витрин с выразимыми полноцветными принтами." },
  { name: "Бренд", icon: "badge-check", description: "Брендируемые изделия для корпоративных подарков, мерча, промоакций и единых фирменных комплектов." },
  { name: "Подарки", icon: "gift", description: "Универсальные подарочные дизайны для готовых наборов, праздничных полок и быстрой сборки партии." },
];

const catalogHolidays = [
  { name: "Новый год", icon: "snowflake", description: "Новогодние принты для сезонных подарков, корпоративных наборов, маркетплейсов и декабрьских витрин." },
  { name: "14 февраля", icon: "heart", description: "Романтические дизайны для подарочных партий ко Дню святого Валентина и тематических февральских продаж." },
  { name: "8 марта", icon: "flower-2", description: "Весенние принты для подарочных наборов, розничных витрин и корпоративных заказов к 8 марта." },
  { name: "23 февраля", icon: "medal", description: "Сезонная подборка к 23 февраля для подарочных партий, сувенирных полок и корпоративных заявок." },
  { name: "9 мая", icon: "flag", description: "Тематические принты к 9 мая для памятных подарков, сувенирных партий и сезонных витрин." },
  { name: "День учителя", icon: "graduation-cap", description: "Текстильные подарки ко Дню учителя для школьных закупок, классов, родительских комитетов и розницы." },
  { name: "День рождения", icon: "cake", description: "Праздничные принты для универсальных подарков, персональных наборов и круглогодичных витрин." },
  { name: "Пасха", icon: "egg", description: "Пасхальные дизайны для весенних подарочных партий, семейных витрин и сезонных маркетплейс-поставок." },
];

const actualItems = [
  {
    label: "Новый год",
    type: "holiday",
    image: "assets/product-preview-live/opt-22434/3.webp",
  },
  {
    label: "Аниме",
    type: "collection",
    image: "assets/product-preview-live/opt-22441/3.webp",
  },
  {
    label: "8 марта",
    type: "holiday",
    image: "assets/product-preview-live/opt-98081/4.webp",
  },
];

const taxonomyAliases = {
  однотонный: "Однотонные",
  однотонная: "Однотонные",
  однотонное: "Однотонные",
  однотонные: "Однотонные",
  детский: "Детские",
  детская: "Детские",
  детское: "Детские",
  детские: "Детские",
  дети: "Детские",
  животное: "Животные",
  животный: "Животные",
  животные: "Животные",
  мем: "Мемы",
  мемы: "Мемы",
  паттерн: "Паттерны",
  паттерны: "Паттерны",
  цветок: "Цветы",
  цветы: "Цветы",
  именной: "Именные",
  именные: "Именные",
  военный: "Военные",
  военные: "Военные",
  подарок: "Подарки",
  подарки: "Подарки",
  игра: "Игры",
  игры: "Игры",
  "9мая": "9 мая",
  "9 мая": "9 мая",
};

const PRODUCT_STATUSES = ["draft", "published", "hidden", "archive"];
const PRODUCT_STATUS_LABELS = {
  draft: "Черновик",
  published: "Опубликован",
  hidden: "Скрыт",
  archive: "Архив",
};

const defaultSiteContent = {
  brandName: "Sobag Opt",
  brandLogo: "",
  toplinePrimary: "Оптовые партии от 30 000 ₽",
  toplineSecondary: "Печать и пошив под заказ",
  toplineTertiary: "Каталог для селлеров и магазинов",
  navCatalogButton: "каталог",
  navBusinessButton: "условия для бизнеса",
  navMarketplacesButton: "мы на маркетплейсах",
  navAboutButton: "о компании",
  navContactsButton: "контакты",
  cartButton: "корзина",
  heroTitle: "Оптовый текстиль с принтами",
  heroLead:
    "Готовые позиции для продаж и производство под ваш макет: пледы, подушки, наволочки, шопперы и сезонные коллекции для маркетплейсов.",
  heroPrimaryButton: "перейти в каталог",
  heroCustomButton: "изделия с вашим принтом",
  actualTitle: "Актуально",
  heroSpecOneValue: "30 000 ₽",
  heroSpecOneText: "минимальная сумма заказа",
  heroSpecTwoValue: "7 дней",
  heroSpecTwoText: "запуск партии после согласования",
  heroSpecThreeValue: "до 18%",
  heroSpecThreeText: "скидка при заказе",
  benefitOneTitle: "Скидка от суммы заказа",
  benefitOneText: "Чем больше сумма в корзине, тем ниже цена. Скидка пересчитывается сразу.",
  benefitTwoTitle: "Свое производство",
  benefitTwoText: "Печать, пошив, упаковка и подготовка к отгрузке в одном месте.",
  benefitThreeTitle: "Для маркетплейсов",
  benefitThreeText: "Производство, упаковка, штрихкоды, комплектация и поставки партиями.",
  benefitFourTitle: "Прямая связь",
  benefitFourText: "Личный менеджер и общение напрямую с производством по каждому заказу.",
  catalogTitleDefault: "Каталог продукции",
  catalogBackButton: "В каталог",
  catalogHomeTitle: "Выберите категорию",
  catalogHomeSubtitle: "Сначала раздел, потом товары и фильтры",
  catalogActualTitle: "Актуально",
  catalogCollectionsTitle: "Подборки",
  catalogHolidaysTitle: "Праздники",
  filterOpenButton: "открыть фильтры",
  filterCloseButton: "закрыть фильтры",
  requestEyebrow: "Корзина",
  requestTitle: "Оптовый заказ",
  requestEmptyText: "Добавьте товары из каталога",
  requestMinHint: "Минимальная сумма корзины 30 000 ₽.",
  requestSubmitReady: "отправить корзину",
  requestSubmitLocked: "минимум 30 000 ₽",
  wholesaleTitle: "Скидки и условия",
  tierOneLabel: "от 30 000 ₽",
  tierOneValue: "3%",
  tierOneText: "стартовая оптовая скидка",
  tierTwoLabel: "от 70 000 ₽",
  tierTwoValue: "7%",
  tierTwoText: "для регулярных закупок",
  tierThreeLabel: "от 150 000 ₽",
  tierThreeValue: "12%",
  tierThreeText: "для магазинов и селлеров",
  tierFourLabel: "от 300 000 ₽",
  tierFourValue: "18%",
  tierFourText: "индивидуальные условия",
  marketplacesTitle: "Мы на маркетплейсах",
  marketplacesText:
    "Готовые товары Sobag можно смотреть на витринах маркетплейсов, а оптовые партии и индивидуальные принты оформлять через этот сайт.",
  marketplaceOneName: "Wildberries",
  marketplaceOneTitle: "Витрина Sobag",
  marketplaceOneText: "Витрина для просмотра части готового ассортимента Sobag.",
  marketplaceTwoName: "Ozon",
  marketplaceTwoTitle: "Товары в наличии",
  marketplaceTwoText: "Подходит для просмотра готовых коллекций.",
  marketplaceThreeName: "Яндекс Маркет",
  marketplaceThreeTitle: "Проверка ассортимента",
  marketplaceThreeText: "Дополнительный канал для проверки готовых коллекций и наличия.",
  customTitle: "Изделия с вашим принтом",
  customText:
    "Отдельный сценарий для корпоративных клиентов, селлеров и магазинов: загружают задачу, выбирают изделие, тираж, упаковку и получают расчет.",
  customStepOne: "Выбор изделия и ткани",
  customStepTwo: "Проверка макета",
  customStepThree: "Печать и пошив",
  customStepFour: "Упаковка и отгрузка",
  customSubmitButton: "получить расчет",
  businessPageTitle: "Условия для бизнеса",
  businessPageLead:
    "Условия для магазинов, селлеров и корпоративных клиентов: скидка от суммы заказа, производство в одном месте и сопровождение менеджера.",
  businessMinimumTitle: "Минимальный заказ",
  businessMinimumText: "Минимальная сумма для оформления оптовой заявки — 30 000 ₽. До этой суммы товары можно добавлять в корзину, сохранять подборку и готовить заказ к отправке менеджеру.",
  businessDiscountTitle: "Скидка от суммы",
  businessDiscountText: "Скидка пересчитывается автоматически по общей сумме корзины: от 30 000 ₽, 70 000 ₽, 150 000 ₽ и 300 000 ₽. Чем больше партия, тем ниже цена за единицу товара.",
  businessProductionTitle: "Производство и комплектация",
  businessProductionText: "Печать, раскрой, пошив, упаковка, маркировка и подготовка к отгрузке выполняются в одном процессе. Срок запуска партии зависит от тиража, макетов, наличия материалов и подтверждается менеджером.",
  businessManagerTitle: "Связь с менеджером",
  businessManagerText: "После отправки корзины менеджер связывается с покупателем, уточняет наличие, сроки, упаковку, город отгрузки и помогает довести заказ до запуска.",
  businessDocumentsTitle: "Документы и согласования",
  businessDocumentsText: "Реквизиты, счет, макеты, штрихкоды, упаковку и требования маркетплейсов можно согласовать до запуска партии. Финальные условия фиксируются в счете, договоре или переписке с менеджером.",
  aboutPageTitle: "О компании Sobag Opt",
  aboutPageLead:
    "Sobag Opt — B2B-каталог для оптовых продаж текстиля с принтами и заказов на производство под макет покупателя.",
  aboutPageText:
    "Мы работаем с магазинами, селлерами и корпоративными клиентами: помогаем подобрать товар, собрать партию, рассчитать скидку, подготовить упаковку и передать заказ в производство.",
  aboutPageProductionTitle: "Производство текстиля с принтами",
  aboutPageProductionText:
    "Производственный цикл включает печать, раскрой, пошив, контроль качества, упаковку, маркировку и подготовку к отгрузке. Один принт можно выпускать в разных изделиях, размерах и материалах.",
  contactsPageTitle: "Контакты",
  contactsPageLead: "Свяжитесь с отделом опта, чтобы уточнить наличие, сроки запуска партии, упаковку, отгрузку и документы.",
  contactsAddress: "Филиал / производство: г. Курск, ул. Литовская, д. 12",
  contactsLegalAddress: "431815, Республика Мордовия, Атяшевский р-н, село Наборные Сыреси, ул. Крупской, д. 18",
  contactsProductionAddress: "г. Курск, ул. Литовская, д. 12",
  contactsSchedule: "Пн-Пт, 10:00-18:00 по Москве",
  contactsMapButton: "показать на карте",
  howToOrderPageTitle: "Как оформить заказ",
  howToOrderPageLead: "Покупатель собирает товары в корзину, проверяет скидку и отправляет заявку менеджеру.",
  howToOrderPageText:
    "Добавьте нужные варианты товара, перейдите в корзину, заполните контакты и отправьте заказ. Менеджер проверит наличие, сроки, упаковку, документы и подтвердит финальные условия.",
  deliveryPageTitle: "Доставка товара",
  deliveryPageLead: "Способ доставки и город отгрузки согласуются после проверки оптовой заявки.",
  deliveryPageText:
    "Доставка рассчитывается после подтверждения состава заказа, веса, объема и требований к упаковке. Возможны самовывоз, транспортная компания или индивидуальная схема отгрузки.",
  paymentPageTitle: "Оплата товара",
  paymentPageLead: "Оплата фиксируется после согласования заказа, счета и реквизитов.",
  paymentPageText:
    "Для юридических лиц и ИП возможна оплата по счету. Финальный порядок оплаты, резерв товара и документы подтверждает менеджер перед запуском партии.",
  returnsPageTitle: "Возврат товара",
  returnsPageLead: "Вопросы возврата и претензий решаются по согласованным условиям заказа.",
  returnsPageText:
    "Если в партии есть расхождения по количеству, комплектности или качеству, зафиксируйте их фото и описанием. Менеджер проверит обращение и предложит решение.",
  sellerSupportPageTitle: "Поддержка селлеров",
  sellerSupportPageLead: "Помощь с упаковкой, маркировкой и подготовкой партий для маркетплейсов.",
  sellerSupportPageText:
    "Можно согласовать штрихкоды, упаковку, комплектацию, маркировку и требования площадок. Детали фиксируются до запуска партии в производство.",
  wholesalePageTitle: "Оптовые партии",
  wholesalePageLead: "Партии собираются из готовых позиций и изделий под макет клиента.",
  wholesalePageText:
    "Оптовая партия может включать разные изделия, размеры, материалы и принты. Скидка зависит от суммы корзины, а сроки запуска подтверждаются после проверки состава заказа.",
  footerBrand: "SOBAG OPT",
  footerText: "B2B-каталог для оптовых заказов текстиля с принтами, производства под макет и поставок партиями.",
  footerSalesLabel: "Отдел опта",
  footerEmail: "ip.burago@yandex.ru",
  footerPhone: "+7 901 879-41-62",
  footerCompanyTitle: "Компания",
  footerCompanyLinks: "О компании|Контакты|Политика конфиденциальности|Согласие на обработку персональных данных|Пользовательское соглашение",
  footerClientsTitle: "Клиентам",
  footerClientsLinks: "Как оформить заказ|Доставка товара|Оплата товара|Возврат товара|Изделия с вашим принтом",
  footerPartnersTitle: "Партнерам",
  footerPartnersLinks: "Условия для бизнеса|Мы на маркетплейсах|Поддержка селлеров|Оптовые партии",
  footerContactsTitle: "Контакты",
  footerAddress: "Филиал / производство: г. Курск, ул. Литовская, д. 12",
  cartPageTitle: "Корзина",
  cartPageBackButton: "вернуться в каталог",
  cartPageEmptyTitle: "Корзина пока пустая",
  cartPageEmptyText: "Добавьте товары из каталога, чтобы увидеть расчет оптовой скидки.",
  cartDiscountTitle: "Скидка",
  cartPromoTitle: "Промокод",
  cartPromoPlaceholder: "Введите промокод",
  cartPromoButton: "применить",
  cartCheckoutButton: "оформить заказ",
  checkoutTitle: "Контакты покупателя",
  checkoutSubmitButton: "отправить заказ",
  heroImages: ["assets/production-hero-1.png", "assets/production-workshop-1.png", "assets/production-hero-1.png"],
  catalogCategories,
  catalogCollections,
  catalogHolidays,
  actualSlides: actualItems,
};

const siteTextFields = [
  { key: "toplinePrimary", label: "Верхняя строка 1" },
  { key: "toplineSecondary", label: "Верхняя строка 2" },
  { key: "toplineTertiary", label: "Верхняя строка 3" },
  { key: "navCatalogButton", label: "Кнопка шапки: каталог" },
  { key: "navBusinessButton", label: "Кнопка шапки: условия" },
  { key: "navMarketplacesButton", label: "Кнопка шапки: маркетплейсы" },
  { key: "navAboutButton", label: "Кнопка шапки: о компании" },
  { key: "navContactsButton", label: "Кнопка шапки: контакты" },
  { key: "cartButton", label: "Кнопка шапки: корзина" },
  { key: "heroTitle", label: "Заголовок главной" },
  { key: "heroLead", label: "Текст главной", multiline: true, wide: true },
  { key: "heroPrimaryButton", label: "Кнопка главной: каталог" },
  { key: "heroCustomButton", label: "Кнопка главной: свой принт" },
  { key: "actualTitle", label: "Название блока актуально" },
  { key: "heroSpecOneValue", label: "Преимущество 1: цифра" },
  { key: "heroSpecOneText", label: "Преимущество 1: подпись" },
  { key: "heroSpecTwoValue", label: "Преимущество 2: цифра" },
  { key: "heroSpecTwoText", label: "Преимущество 2: подпись" },
  { key: "heroSpecThreeValue", label: "Преимущество 3: цифра" },
  { key: "heroSpecThreeText", label: "Преимущество 3: подпись" },
  { key: "benefitOneTitle", label: "Блок преимуществ 1: заголовок" },
  { key: "benefitOneText", label: "Блок преимуществ 1: текст", multiline: true, wide: true },
  { key: "benefitTwoTitle", label: "Блок преимуществ 2: заголовок" },
  { key: "benefitTwoText", label: "Блок преимуществ 2: текст", multiline: true, wide: true },
  { key: "benefitThreeTitle", label: "Блок преимуществ 3: заголовок" },
  { key: "benefitThreeText", label: "Блок преимуществ 3: текст", multiline: true, wide: true },
  { key: "benefitFourTitle", label: "Блок преимуществ 4: заголовок" },
  { key: "benefitFourText", label: "Блок преимуществ 4: текст", multiline: true, wide: true },
  { key: "catalogTitleDefault", label: "Каталог: заголовок" },
  { key: "catalogBackButton", label: "Каталог: кнопка назад к категориям" },
  { key: "catalogHomeTitle", label: "Каталог: заголовок категорий" },
  { key: "catalogHomeSubtitle", label: "Каталог: подпись категорий" },
  { key: "catalogActualTitle", label: "Каталог: актуально" },
  { key: "catalogCollectionsTitle", label: "Каталог: подборки" },
  { key: "catalogHolidaysTitle", label: "Каталог: праздники" },
  { key: "filterOpenButton", label: "Кнопка: открыть фильтры" },
  { key: "filterCloseButton", label: "Кнопка: закрыть фильтры" },
  { key: "requestEyebrow", label: "Мини-корзина: метка" },
  { key: "requestTitle", label: "Мини-корзина: заголовок" },
  { key: "requestEmptyText", label: "Мини-корзина: пустая корзина" },
  { key: "requestMinHint", label: "Мини-корзина: минимальная сумма" },
  { key: "requestSubmitReady", label: "Кнопка: отправить корзину" },
  { key: "requestSubmitLocked", label: "Кнопка: минимум не набран" },
  { key: "wholesaleTitle", label: "Оптовый блок: заголовок" },
  { key: "tierOneLabel", label: "Скидка 1: условие" },
  { key: "tierOneValue", label: "Скидка 1: процент" },
  { key: "tierOneText", label: "Скидка 1: подпись" },
  { key: "tierTwoLabel", label: "Скидка 2: условие" },
  { key: "tierTwoValue", label: "Скидка 2: процент" },
  { key: "tierTwoText", label: "Скидка 2: подпись" },
  { key: "tierThreeLabel", label: "Скидка 3: условие" },
  { key: "tierThreeValue", label: "Скидка 3: процент" },
  { key: "tierThreeText", label: "Скидка 3: подпись" },
  { key: "tierFourLabel", label: "Скидка 4: условие" },
  { key: "tierFourValue", label: "Скидка 4: процент" },
  { key: "tierFourText", label: "Скидка 4: подпись" },
  { key: "marketplacesTitle", label: "Маркетплейсы: заголовок" },
  { key: "marketplacesText", label: "Маркетплейсы: описание", multiline: true, wide: true },
  { key: "marketplaceOneName", label: "Маркетплейс 1: площадка" },
  { key: "marketplaceOneTitle", label: "Маркетплейс 1: заголовок" },
  { key: "marketplaceOneText", label: "Маркетплейс 1: текст" },
  { key: "marketplaceTwoName", label: "Маркетплейс 2: площадка" },
  { key: "marketplaceTwoTitle", label: "Маркетплейс 2: заголовок" },
  { key: "marketplaceTwoText", label: "Маркетплейс 2: текст" },
  { key: "marketplaceThreeName", label: "Маркетплейс 3: площадка" },
  { key: "marketplaceThreeTitle", label: "Маркетплейс 3: заголовок" },
  { key: "marketplaceThreeText", label: "Маркетплейс 3: текст" },
  { key: "customTitle", label: "Свой принт: заголовок" },
  { key: "customText", label: "Свой принт: описание", multiline: true, wide: true },
  { key: "customStepOne", label: "Свой принт: шаг 1" },
  { key: "customStepTwo", label: "Свой принт: шаг 2" },
  { key: "customStepThree", label: "Свой принт: шаг 3" },
  { key: "customStepFour", label: "Свой принт: шаг 4" },
  { key: "customSubmitButton", label: "Кнопка: получить расчет" },
  { key: "businessPageTitle", label: "Условия для бизнеса: заголовок" },
  { key: "businessPageLead", label: "Условия для бизнеса: вступление", multiline: true, wide: true },
  { key: "businessMinimumTitle", label: "Условия: минимальный заказ" },
  { key: "businessMinimumText", label: "Условия: текст минимального заказа", multiline: true, wide: true },
  { key: "businessDiscountTitle", label: "Условия: скидка" },
  { key: "businessDiscountText", label: "Условия: текст скидки", multiline: true, wide: true },
  { key: "businessProductionTitle", label: "Условия: производство" },
  { key: "businessProductionText", label: "Условия: текст производства", multiline: true, wide: true },
  { key: "businessManagerTitle", label: "Условия: менеджер" },
  { key: "businessManagerText", label: "Условия: текст менеджера", multiline: true, wide: true },
  { key: "businessDocumentsTitle", label: "Условия: документы" },
  { key: "businessDocumentsText", label: "Условия: текст документов", multiline: true, wide: true },
  { key: "aboutPageTitle", label: "О компании: заголовок" },
  { key: "aboutPageLead", label: "О компании: вступление", multiline: true, wide: true },
  { key: "aboutPageText", label: "О компании: основной текст", multiline: true, wide: true },
  { key: "aboutPageProductionTitle", label: "О компании: блок производства" },
  { key: "aboutPageProductionText", label: "О компании: текст производства", multiline: true, wide: true },
  { key: "contactsPageTitle", label: "Контакты: заголовок" },
  { key: "contactsPageLead", label: "Контакты: вступление", multiline: true, wide: true },
  { key: "contactsAddress", label: "Контакты: общий адрес" },
  { key: "contactsLegalAddress", label: "Контакты: юридический адрес" },
  { key: "contactsProductionAddress", label: "Контакты: адрес производства" },
  { key: "contactsSchedule", label: "Контакты: график" },
  { key: "contactsMapButton", label: "Контакты: кнопка карты" },
  { key: "howToOrderPageTitle", label: "Как оформить заказ: заголовок" },
  { key: "howToOrderPageLead", label: "Как оформить заказ: вступление", multiline: true, wide: true },
  { key: "howToOrderPageText", label: "Как оформить заказ: текст", multiline: true, wide: true },
  { key: "deliveryPageTitle", label: "Доставка: заголовок" },
  { key: "deliveryPageLead", label: "Доставка: вступление", multiline: true, wide: true },
  { key: "deliveryPageText", label: "Доставка: текст", multiline: true, wide: true },
  { key: "paymentPageTitle", label: "Оплата: заголовок" },
  { key: "paymentPageLead", label: "Оплата: вступление", multiline: true, wide: true },
  { key: "paymentPageText", label: "Оплата: текст", multiline: true, wide: true },
  { key: "returnsPageTitle", label: "Возврат: заголовок" },
  { key: "returnsPageLead", label: "Возврат: вступление", multiline: true, wide: true },
  { key: "returnsPageText", label: "Возврат: текст", multiline: true, wide: true },
  { key: "sellerSupportPageTitle", label: "Поддержка селлеров: заголовок" },
  { key: "sellerSupportPageLead", label: "Поддержка селлеров: вступление", multiline: true, wide: true },
  { key: "sellerSupportPageText", label: "Поддержка селлеров: текст", multiline: true, wide: true },
  { key: "wholesalePageTitle", label: "Оптовые партии: заголовок" },
  { key: "wholesalePageLead", label: "Оптовые партии: вступление", multiline: true, wide: true },
  { key: "wholesalePageText", label: "Оптовые партии: текст", multiline: true, wide: true },
  { key: "footerBrand", label: "Подвал: название" },
  { key: "footerText", label: "Подвал: описание", multiline: true, wide: true },
  { key: "footerSalesLabel", label: "Подвал: отдел" },
  { key: "footerEmail", label: "Подвал: email" },
  { key: "footerPhone", label: "Подвал: телефон" },
  { key: "footerCompanyTitle", label: "Подвал: колонка Компания" },
  { key: "footerCompanyLinks", label: "Подвал: ссылки Компания через |", multiline: true, wide: true },
  { key: "footerClientsTitle", label: "Подвал: колонка Клиентам" },
  { key: "footerClientsLinks", label: "Подвал: ссылки Клиентам через |", multiline: true, wide: true },
  { key: "footerPartnersTitle", label: "Подвал: колонка Партнерам" },
  { key: "footerPartnersLinks", label: "Подвал: ссылки Партнерам через |", multiline: true, wide: true },
  { key: "footerContactsTitle", label: "Подвал: колонка Контакты" },
  { key: "footerAddress", label: "Подвал: адрес", multiline: true, wide: true },
  { key: "cartPageTitle", label: "Страница корзины: заголовок" },
  { key: "cartPageBackButton", label: "Страница корзины: кнопка назад" },
  { key: "cartPageEmptyTitle", label: "Страница корзины: пустая корзина" },
  { key: "cartPageEmptyText", label: "Страница корзины: текст пустой корзины", multiline: true, wide: true },
  { key: "cartDiscountTitle", label: "Страница корзины: скидка" },
  { key: "cartPromoTitle", label: "Страница корзины: промокод" },
  { key: "cartPromoPlaceholder", label: "Страница корзины: поле промокода" },
  { key: "cartPromoButton", label: "Страница корзины: кнопка промокода" },
  { key: "cartCheckoutButton", label: "Страница корзины: кнопка оформления" },
  { key: "checkoutTitle", label: "Форма заказа: заголовок" },
  { key: "checkoutSubmitButton", label: "Форма заказа: кнопка отправки" },
];


const siteTextFieldPages = [
  {
    title: "Общие настройки сайта",
    note: "Название, верхнее меню, кнопки шапки и корзина. Эти элементы видны почти на всех страницах.",
    keys: ["toplinePrimary", "toplineSecondary", "toplineTertiary", "navCatalogButton", "navBusinessButton", "navMarketplacesButton", "navAboutButton", "navContactsButton", "cartButton"],
  },
  {
    title: "Страница: главная",
    note: "Первый экран, блок Актуально, преимущества и условия для бизнеса на главной странице.",
    keys: ["heroTitle", "heroLead", "heroPrimaryButton", "heroCustomButton", "actualTitle", "heroSpecOneValue", "heroSpecOneText", "heroSpecTwoValue", "heroSpecTwoText", "heroSpecThreeValue", "heroSpecThreeText", "benefitOneTitle", "benefitOneText", "benefitTwoTitle", "benefitTwoText", "benefitThreeTitle", "benefitThreeText", "benefitFourTitle", "benefitFourText", "wholesaleTitle", "tierOneLabel", "tierOneValue", "tierOneText", "tierTwoLabel", "tierTwoValue", "tierTwoText", "tierThreeLabel", "tierThreeValue", "tierThreeText", "tierFourLabel", "tierFourValue", "tierFourText"],
  },
  {
    title: "Страница: каталог",
    note: "Главная каталога, фильтры и боковая мини-корзина внутри каталога.",
    keys: ["catalogTitleDefault", "catalogBackButton", "catalogHomeTitle", "catalogHomeSubtitle", "catalogActualTitle", "catalogCollectionsTitle", "catalogHolidaysTitle", "filterOpenButton", "filterCloseButton", "requestEyebrow", "requestTitle", "requestEmptyText", "requestMinHint", "requestSubmitReady", "requestSubmitLocked"],
  },
  {
    title: "Страница: мы на маркетплейсах",
    note: "Отдельная страница со ссылками и описаниями витрин.",
    keys: ["marketplacesTitle", "marketplacesText", "marketplaceOneName", "marketplaceOneTitle", "marketplaceOneText", "marketplaceTwoName", "marketplaceTwoTitle", "marketplaceTwoText", "marketplaceThreeName", "marketplaceThreeTitle", "marketplaceThreeText"],
  },
  {
    title: "Страница: изделия с вашим принтом",
    note: "Текст калькулятора/брифа для заказов под макет клиента.",
    keys: ["customTitle", "customText", "customStepOne", "customStepTwo", "customStepThree", "customStepFour", "customSubmitButton"],
  },
  {
    title: "Страница: условия для бизнеса",
    note: "Отдельная страница с правилами опта, скидками, производством и работой менеджера.",
    keys: ["businessPageTitle", "businessPageLead", "businessMinimumTitle", "businessMinimumText", "businessDiscountTitle", "businessDiscountText", "businessProductionTitle", "businessProductionText", "businessManagerTitle", "businessManagerText", "businessDocumentsTitle", "businessDocumentsText"],
  },
  {
    title: "Страница: о компании",
    note: "Отдельная страница с описанием компании, производства и оптового направления.",
    keys: ["aboutPageTitle", "aboutPageLead", "aboutPageText", "aboutPageProductionTitle", "aboutPageProductionText"],
  },
  {
    title: "Страница: контакты",
    note: "Отдельная страница контактов, адрес для Яндекс Карт и график работы.",
    keys: ["contactsPageTitle", "contactsPageLead", "contactsAddress", "contactsLegalAddress", "contactsProductionAddress", "contactsSchedule", "contactsMapButton"],
  },
  {
    title: "Страница: как оформить заказ",
    note: "Информационный раздел из подвала.",
    keys: ["howToOrderPageTitle", "howToOrderPageLead", "howToOrderPageText"],
  },
  {
    title: "Страница: доставка товара",
    note: "Информационный раздел из подвала.",
    keys: ["deliveryPageTitle", "deliveryPageLead", "deliveryPageText"],
  },
  {
    title: "Страница: оплата товара",
    note: "Информационный раздел из подвала.",
    keys: ["paymentPageTitle", "paymentPageLead", "paymentPageText"],
  },
  {
    title: "Страница: возврат товара",
    note: "Информационный раздел из подвала.",
    keys: ["returnsPageTitle", "returnsPageLead", "returnsPageText"],
  },
  {
    title: "Страница: поддержка селлеров",
    note: "Информационный раздел из подвала.",
    keys: ["sellerSupportPageTitle", "sellerSupportPageLead", "sellerSupportPageText"],
  },
  {
    title: "Страница: оптовые партии",
    note: "Информационный раздел из подвала.",
    keys: ["wholesalePageTitle", "wholesalePageLead", "wholesalePageText"],
  },
  {
    title: "Страница: корзина и оформление",
    note: "Отдельная страница корзины, промокод и модальное окно оформления заказа.",
    keys: ["cartPageTitle", "cartPageBackButton", "cartPageEmptyTitle", "cartPageEmptyText", "cartDiscountTitle", "cartPromoTitle", "cartPromoPlaceholder", "cartPromoButton", "cartCheckoutButton", "checkoutTitle", "checkoutSubmitButton"],
  },
  {
    title: "Контакты и подвал",
    note: "Нижний блок сайта и контактные данные отдела опта.",
    keys: ["footerBrand", "footerText", "footerSalesLabel", "footerEmail", "footerPhone", "footerCompanyTitle", "footerCompanyLinks", "footerClientsTitle", "footerClientsLinks", "footerPartnersTitle", "footerPartnersLinks", "footerContactsTitle", "footerAddress"],
  },
];

const adminPageAnchors = [
  "global",
  "home",
  "catalog",
  "marketplaces",
  "custom",
  "business",
  "about",
  "contacts",
  "how-to-order",
  "delivery",
  "payment",
  "returns",
  "seller-support",
  "wholesale",
  "cart",
  "footer",
];

const siteTextFieldGroups = siteTextFieldPages.map((group, index) => ({
  ...group,
  anchor: adminPageAnchors[index] || `section-${index + 1}`,
  fields: group.keys.map((key) => siteTextFields.find((field) => field.key === key)).filter(Boolean),
}));

const productDrafts = [];
const FAVORITES_KEY = "sobag.favorites";
const FAVORITES_PREFIX = "sobag.favorites.";
const PROTOTYPE_PRODUCT_IDS = new Set([
  "aurora-cats",
  "pixel-quest",
  "winter-gift",
  "brand-line",
  "army-supply",
  "cooler-love",
  "meme-cloud",
  "march-bloom",
  "teacher-pattern",
  "space-luggage",
  "anime-cover",
  "shoe-cyber",
  "shoe-flower",
  "cooler-brand",
  "cooler-newyear",
  "plaid-animal",
  "plaid-meme",
  "name-stars",
]);

const STORAGE = {
  user: "sobag.currentUser",
  users: "sobag.users",
  products: "sobag.products.v8",
  content: "sobag.siteContent.v1",
  importBatches: "sobag.importBatches.v1",
  theme: "sobag.theme.v1",
  guestCart: "sobag.cart.guest",
  guestSavedCarts: "sobag.savedCarts.guest",
  savedCartsPrefix: "sobag.savedCarts.",
  orders: "sobag.orders.v1",
  recentProducts: "sobag.recentProducts.v1",
};
const PUBLIC_API_CACHE_PREFIX = "sobag.publicApiCache.v1.";
const PUBLIC_API_CACHE_TTL_MS = 30 * 60 * 1000;
const PUBLIC_API_CACHE_MAX_ENTRIES = 80;

const productTemplateColumns = [
  { key: "name", label: "Название" },
  { key: "baseSku", label: "Основной артикул" },
  { key: "category", label: "Категории" },
  { key: "theme", label: "Основная подборка" },
  { key: "collections", label: "Подборки" },
  { key: "holidays", label: "Праздники" },
  { key: "tags", label: "Теги" },
  { key: "types", label: "Типы товара" },
  { key: "sizes", label: "Размеры" },
  { key: "materials", label: "Материалы" },
  { key: "basePrice", label: "Базовая цена" },
  { key: "image", label: "URL фото" },
  { key: "status", label: "Статус публикации" },
  { key: "stock", label: "Статус наличия" },
];

const productExportOnlyColumns = [
  { key: "description", label: "Краткое описание" },
  { key: "detailDescription", label: "Описание в карточке" },
  { key: "badge", label: "Бейдж" },
  { key: "popular", label: "Популярность" },
  { key: "photoFolder", label: "Папка фото" },
  { key: "gallery", label: "Фото галереи" },
];

const productExportColumns = [...productTemplateColumns, ...productExportOnlyColumns];

const productColumnAliases = {
  baseSku: ["Начальный артикул", "Артикул", "Базовый артикул"],
  category: ["Категория", "Категории"],
  image: ["Главное фото", "URL фото", "Фото"],
  theme: ["Тематика", "Основная тематика", "Основная подборка"],
  collections: ["Тематики", "Подборки"],
  holidays: ["Праздник", "Праздники"],
  status: ["Публикация", "Публикационный статус", "status"],
  stock: ["Статус наличия", "Статус", "stock"],
  photoFolder: ["Папка", "Папка фото", "Папка с фото"],
};

const variantPriceExportColumns = [
  "Основной артикул",
  "Артикул варианта",
  "Название варианта",
  "Тип товара",
  "Размер",
  "Материал",
  "Цена варианта",
  "Категории",
  "Подборки",
  "Праздники",
  "Теги",
  "Папка фото",
];

  window.SobagAppData = {
    TYPE_OPTIONS,
    SIZE_OPTIONS,
    MATERIAL_OPTIONS,
    sizeFactors,
    materialFactors,
    typeFactors,
    quantityTiers,
    MIN_CART_TOTAL,
    basketDiscountTiers,
    catalogCategories,
    catalogCollections,
    catalogHolidays,
    actualItems,
    taxonomyAliases,
    PRODUCT_STATUSES,
    PRODUCT_STATUS_LABELS,
    defaultSiteContent,
    siteTextFields,
    siteTextFieldPages,
    adminPageAnchors,
    siteTextFieldGroups,
    productDrafts,
    FAVORITES_KEY,
    FAVORITES_PREFIX,
    PROTOTYPE_PRODUCT_IDS,
    STORAGE,
    PUBLIC_API_CACHE_PREFIX,
    PUBLIC_API_CACHE_TTL_MS,
    PUBLIC_API_CACHE_MAX_ENTRIES,
    productTemplateColumns,
    productExportOnlyColumns,
    productExportColumns,
    productColumnAliases,
    variantPriceExportColumns
  };
})();
